project:
  type: website

website:
  title: "GCSA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: demographics.ipynb
        text: Demographics
      - href: crime_stats.ipynb
        text: Crime Statistics
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



